export const API_BASE_URL = 'http://192.168.0.131:5000/api';
//export const TIMEOUT = 30000; // 30 seconds

export const ENDPOINTS = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  LOGOUT: '/auth/logout',
  REFRESH_TOKEN: '/auth/refresh-token',
  VERIFY_EMAIL: (token: string) => `/auth/verify-email/${token}`,
  FORGOT_PASSWORD: '/auth/forgot-password',
  PASSWORD_RESET: (token: string) => `/auth/reset-password/${token}`,
  ALL_AVAILABLE_TRIPS: '/bus-trip/all',
  AVAILABLE_DATES: '/bus-trip/available-dates', 
  AVAILABLE_BUSES_FOR_DATE: '/bus-trip/available-buses', 
  BUS_TRIPS: "/bus-trip",
  BOOK_BUS: '/booking/book-bus',
  //TRIPS_ROUTES_CREATE:'/create',
  BUS_TRIPS_ADMIN:'',
  BUS_TRIPS_CREATE:'',
  BUS_TRIP_UPDATE:(id: string) => `/update-bus-trip/${id}`,
  BUS_TRIP_DELETE:(id: string) => `/delete-bus-trip/${id}`,
  USER_SCHEDULED_BUS_TRIPS:'/bus-trip/scheduled-bus-trips',
  USER_SCHEDULED_BUS_TRIPS_ID:(id: number)=>`/bus-trip/one-scheduled-bus-trip-with-details/${id}`,
  TRIP_DETAILS: (id: string) => `/trips/${id}`,
  BOOKING_DETAILS: (id: string) => `/booking/${id}`,
  LOCATIONS: '/locations',
  USER_PROFILE: '/users/profile',
  BUSES: '/bus',
  DRIVERS: '/driver',
};
